main: com.alkmoeba.superkits.SuperKits

name: SuperKits
version: 1.9.6
author: AmoebaMan And Gummy
description: The complete kit plugin
depend: [Vault]

commands:
  debug:
    description: Give a kit to a player
    usage: /givekit <player> <kit-name>
    permission: superkits.give
    permission-message: You don't have permission to give kits
  givekit:
    description: Give a kit to a player
    usage: /givekit <player> <kit-name>
    permission: superkits.give
    permission-message: You don't have permission to give kits
    
  kit:
    description: Get a kit
    usage: /kit <kit-name>
    permission: superkits.take
    permission-message: You don't have permission to take kits
    
  kitlist:
    description: List the available kits
    usage: /kitlist
    permission: superkits.list
    permission-message: You don't have permission to view kits
    
  kitinfo:
    description: Displays info about a kit
    usage: /kitinfo <kit>
    permission: superkits.list
    permission-message: You don't have permissions to get info about kits
    
  reloadkits:
    description: Reloads kits from kits.yml
    usage: /reloadkits
    permission: superkits.reload
    permission-message: You don't have permission to reload kits
        
permissions:

  superkits.*:
    description: Gives access to all SuperKits permissions
    children:
      superkits.give: true
      superkits.take: true
      superkits.list: true
      superkits.reload: true
      superkits.kit.*: true
      superkits.notimeout: true
      superkits.createsign: true
    
  superkits.give:
    description: Allows the player to give kits to other players
    default: op
    
  superkits.take:
    description: Allows the player to take kits via command
    default: true
    
  superkits.list:
    description: Allows the player to see the kits available to them
    default: true
    
  superkits.reload:
    description: Allows the player to reload the kits file
    default: op
    
  superkits.kit.*:
    description: Grants permission for all kits
    default: op
    
  superkits.shorttimeout:
    description: Reduces the timeouts of all kits (except global-timeouts) to 1/3 their configured values for the player
    default: false
    
  superkits.notimeout:
    description: Removes the timeouts of all kits entirely for the player
    default: op
    
  superkits.createsign:
    description: Allows the player to create and break kit selection signs
    default: op